name: mongoauth
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
  
dependencies:
  rxdart: ^0.24.1
  mongo_dart: ^0.4.3
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
